algoritmo "tabuada basica arrumada"

var

   n, i, final : inteiro

inicio

    final <- 0
    escreva("Deseja a tabuada para qual valor: ")
    leia(n)
    
// ele pega o valor de n e multiplica por i, que vai de 1 a 10, e o resultado é guardado em final, depois ele imprime o resultado
        para i de 1 ate 10 faca
            final <- n * i
            escreval(n, "*", i, " = ", final)
         fimpara

fimalgoritmo